### PR TITLE
fix /tracks related routing bug

### LINKED ISSUE #278: bug: Blank page when user clicks on slides button.
**Describe the bug**

**To Reproduce**
1. Click on the slides button when you go to the course
2. It shows a blank page

**Expected behavior**
- It should show the slides.

**Screenshots or GIFs**
[screen-capture.webm](https://github.com/code100x/daily-code/assets/32411707/8f912396-42d9-458e-8a4a-11dcbaf40546)

**Info (please complete the following information):**
 - Chrome

 - Version 123.0.6312.122 (Official Build) (64-bit)

**Additional context**
URL seems to be wrong - `https://projects.100xdevs.com/tracks/ABEC/[object%20Promise]`

### PR DESCRIPTION
**Pull request by N4r35h**
[dailycode_track_fix.webm](https://github.com/code100x/daily-code/assets/45840495/157cb223-63fa-4e2e-ba6f-813dc23da725)

### PR Fixes:
- 1 if user visits `/tracks/<track>/<problem>` where track or problem is invalid we will properly show the 404 error page (in prod nothing was done just a blank page was shown)
- 2 if user visits `/tracks/<track>` we correctly resolve and redirect to `/tracks/<track>/<problem>` (in prod we didnt resolve the promise and hence redirected to `/tracks/<track>/[object%20Promise]`)

Resolves #278 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

File: apps/web/components/RedirectToLastSolved.tsx [hunk 1]
```diff
@@ -10,12 +10,9 @@ export const RedirectToLastSolved = ({ trackId }: { trackId: string }) => {
...
   useEffect(() => {
-    const problemId = getFirstProblemForTrack(trackId);
-    try {
+    getFirstProblemForTrack(trackId).then((problemId) => {
       router.replace(`/tracks/${trackId}/${problemId}`);
-    } catch (e) {
-      console.error(e);
-    }
+    });
   }, [trackId]);
```
Comment (Shriom-Trivedi) [inline apps/web/components/RedirectToLastSolved.tsx:16]: @N4r35h if the trackId is coming as a prop then we can rule it out of the dependency, right? Since it's never going to change during the component lifecycle.

File: apps/web/components/RedirectToLastSolved.tsx [hunk 2]
```diff
@@ -10,12 +10,9 @@ export const RedirectToLastSolved = ({ trackId }: { trackId: string }) => {
   const router = useRouter();
 
   useEffect(() => {
-    const problemId = getFirstProblemForTrack(trackId);
-    try {
+    getFirstProblemForTrack(trackId).then((problemId) => {
```
Comment (Shriom-Trivedi) [inline apps/web/components/RedirectToLastSolved.tsx:13]: @N4r35h you can add a catch condition here.

**Review by Shriom-Trivedi — COMMENTED** [review]
Hi @N4r35h I've left a few comments, please let me know your thoughts!

**Comment by hkirat** [comment]
Thankyou
/bounty $5

File: apps/web/components/RedirectToLastSolved.tsx (hunk 1 above)
Comment (N4r35h) [reply apps/web/components/RedirectToLastSolved.tsx:16]: this is correct, since this has been merged and this doesn't alter the outcome what so ever lets just hope someone in the future removes it

File: apps/web/components/RedirectToLastSolved.tsx (hunk 2 above)
Comment (N4r35h) [reply apps/web/components/RedirectToLastSolved.tsx:13]: a catch condition would not be required, as the getFirstProblemForTrack function itself has a try catch inside it and returns null if the database call fails for some werid reason, in that case we would redirect to /<track>/null and show the error page its not the best but it would be a very rare case
